openapi: 3.0.0
servers:
  - description: APIHub API Auto Mocking court-hearing-cases
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-courthearing-cases/0.0.0

info:
  title: Common Platform API Crime Court Hearing Cases
  description: API to retrieve court hearing case data, including defendants, offences, and results.
  version: 0.0.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /cases/{case_id}/results:
    get:
      description: Retrieve results directly associated with a case.
      operationId: getCaseLevelResults
      tags:
        - Cases
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
          description: Unique identifier for the case
      responses:
        '200':
          description: Case-level results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CaseJudiciaryResponse"
        '404':
          description: Case not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    CaseJudiciaryResponse:
      type: object
      properties:
        caseResults:
          type: array
          items:
            $ref: "#/components/schemas/CaseJudiciaryResult"

    CaseJudiciaryResult:
      type: object
      title: CaseJudiciaryResult
      description: Case-level Judiciary Result
      properties:
        resultText:
          type: string
          title: Judiciary Result
          description: Result
          default: ""
          example: "This is the example outcome of case results"
      required:
        - resultText
      additionalProperties: false

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Machine-readable error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error context
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
          description: Unique identifier for error tracing