openapi: 3.0.0
servers:
  - description: APIHub API Auto Mocking court-hearing-cases
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-courthearing-cases/0.0.0

info:
  title: Crime Court Hearing Cases API
  description: API to retrieve court hearing case data, including defendants, offences, and results.
  version: 0.0.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /cases/{case_id}/results:
    get:
      description: Retrieve results directly associated with a case.
      operationId: getCaseLevelResults
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
          description: Unique identifier for the case
      responses:
        '200':
          description: Case-level results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CaseJudiciaryResponse"
        '404':
          description: Case not found
        '400':
          description: bad input parameter
components:
  schemas:
    CaseJudiciaryResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/CaseJudiciaryResult"

    CaseJudiciaryResult:
      type: object
      title: CaseJudiciaryResult
      description: Case-level Judiciary Result
      properties:
        resultText:
          type: string
          title: Judiciary Result
          description: Result
          default: ""
      required:
        - resultText
      additionalProperties: false