openapi: 3.0.0
servers:

  - description: APIHub Auto Mocking Cases API
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-cases/0.0.1
 
info:
  title: API CP Crime Cases
  description: Read-only API to retrieve case data, including defendants, offences, and results.
  version: 0.0.1
  contact:
    email: no-reply@hmcts.com
  license:
    name: Apache 2.0
    url: 'https://opensource.org/licenses/MIT'
 
paths:
  /cases:
    get:
      description: Retrieve a list of all cases.
      operationId: getCases
      tags:
        - Cases
      responses:
        '200':
          description: List of cases
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-cases/refs/heads/main/openapi/v0.0.1/cases.200.schema.json"
        '400':
          description: Bad request
 
  /cases/{case_id}:
    get:
      description: Retrieve a specific case by ID.
      operationId: getCaseById
      tags:
        - Cases
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
          description: Unique identifier for the case
      responses:
        '200':
          description: Case details
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-cases/refs/heads/main/openapi/v0.0.1/case.200.schema.json"
        '404':
          description: Case not found
          
  
  /cases/{case_id}/results:
    get:
      description: Retrieve results directly associated with a case.
      operationId: getCaseLevelResults
      tags:
        - Results
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
          description: Unique identifier for the case
          
      responses:
        '200':
          description: Case-level results
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-cases/refs/heads/main/openapi/v0.0.1/caseresults.200.schema.json"
              example:
                - resultText: "Guilty plea accepted by the court."
                - resultText: "Sentenced to 12 months custody."
                - resultText: "Fine of £500 imposed."  
                
        '404':
          description: Case not found
 
  /cases/{case_id}/defendants:
    get:
      description: Retrieve a list of defendants for a given case.
      operationId: getDefendantsByCase
      tags:
        - Defendants
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
          description: Case ID
      responses:
        '200':
          description: List of defendants
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-cases/refs/heads/main/openapi/v0.0.1/defendants.200.schema.json"
              example:
                defendants:
                  - defendantId: "ba7c37c4-ef33-4bbf-8c3c-3942bfea0f11"
                    name: "Jane Doe"
                  - defendantId: "92a6b634-6fbd-4f3d-a1c7-328a2feeff99"
                    name: "John Smith"
        '404':
          description: Case not found
 
  /cases/{case_id}/defendants/{defendant_id}/offences:
    get:
      description: Retrieve offences for a specific defendant in a case.
      operationId: getOffencesByDefendant
      tags:
        - Offences
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
        - in: path
          name: defendant_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of offences
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-cases/refs/heads/main/openapi/v0.0.1/offences.200.schema.json"
              example:
                offences:
                  - "a4fbc7d2-9df4-4efc-9c6d-91e58e43b9fc"
                  - "bb23fd0c-54de-41c4-8108-22a34b8fe9b0"
                  - "f3f7f7cc-e21c-4d5d-a147-b7d3e6e8d70f"
                  
                  
        '404':
          description: Defendant or case not found
 
  /cases/{case_id}/defendants/{defendant_id}/offences/{offence_id}/results:
    get:
      description: Retrieve results for a specific offence.
      operationId: getResultsByOffence
      tags:
        - Results
      parameters:
        - in: path
          name: case_id
          required: true
          schema:
            type: string
        - in: path
          name: defendant_id
          required: true
          schema:
            type: string
        - in: path
          name: offence_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offence results
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-cases/refs/heads/main/openapi/v0.0.1/offenceresults.200.schema.json"
              example:
                - resultText: "Guilty plea accepted by the court."
                - resultText: "Sentenced to 12 months custody."
                - resultText: "Fine of £500 imposed."  
        '404':
          description: Offence not found